### ISSUE TITLE
Go/wasm port?

### ISSUE THREAD

**Issue by HuckRidgeSW** [HuckRidge/hvue#5]
Please 👍 if you're interested in a webassembly port.

I mean, I'll probably do one anyway eventually, wasm being the wave of the future for Go on the browser and all, but more thumbs-ups would probably mean sooner rather than later.

**Comment by HuckRidgeSW** [comment]
+4 out of 6 watchers (one of whom is me) seems sufficient.  I'll see what I can do.

**Comment by HuckRidgeSW** [comment]
I've gotten my feet wet with wasm (thanks Brian Ketelsen and other wasm bloggers) and started on a wasm branch.

Ideally, hvue will be able to run on both compilers via build tags, but we'll see.

**Comment by ghost** [comment]
also been playing with WASM and am impressed by how easy it is to get stuff done.
Vue with golang WASM is going to be very useful, especially considering the pace of VUE

**Comment by ghost** [comment]
@HuckRidgeSW 
wasm branch not public yet ?

**Comment by HuckRidgeSW** [comment]
No, not yet.  Nothing significant to even commit yet, just wanted to make an announcement.  I'll open another issue/PR to track actual progress.
