### ISSUE TITLE
Ability to add in global Vuex store to Vue Config

### ISSUE THREAD

**Issue by mame82** [HuckRidge/hvue#9]
As described here https://vuex.vuejs.org/guide/state.html, Vuex provides a mechanism to "inject" the store (a global single source of truth, closely interacting with Vue) into all child components from the root component.

To achieve this, an additional option called "store" referencing to a global object called "store", too, has to be added.

The following PR adds the missing ComponentOption to do this:

https://github.com/HuckRidgeSW/hvue/pull/6

**Comment by HuckRidgeSW** [comment]
I submitted a change request on #6.

**Comment by mame82** [comment]
As shown here https://github.com/mame82/mvuex/blob/master/example/main.go#L22 and discussed in https://github.com/HuckRidgeSW/hvue/pull/6 this could be achieved without modifying hvue, directly.

So I gonna close the issue. Keep up your work!

Thx, Marcus
